name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out repository
    - uses: actions/checkout@v3

    # Step 2: Set up Python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # Step 3: Install dependencies
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Step 4: Generate statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # Step 5: Debug output - list generated files
    - name: Check generated folder
      run: |
        echo "Listing generated files:"
        ls -al generated || echo "No 'generated' folder found"

    # Step 6: Commit and push to repo
    - name: Commit generated images
      run: |
        git config --global user.name "github-stats[bot]"
        git config --global user.email "github-stats[bot]@users.noreply.github.com"

        # Add only generated images
        git add generated/* || echo "Nothing to add"
        git status
        git commit -m "Update generated files" || echo "No changes to commit"
        git push
